// import { monaco } from "@monaco-editor/react";
import * as monaco from "monaco-editor";

export const provideCompletionItems = (
  model: monaco.editor.ITextModel,
  position: monaco.Position,
  context: monaco.languages.CompletionContext,
  token: monaco.CancellationToken,
): monaco.languages.ProviderResult<monaco.languages.CompletionList> => {
  var word = model.getWordUntilPosition(position);
  var range = {
    startLineNumber: position.lineNumber,
    endLineNumber: position.lineNumber,
    startColumn: word.startColumn,
    endColumn: word.endColumn,
  };
  return {
    suggestions: [
      {
        label: "mov",
        kind: monaco.languages.CompletionItemKind.Keyword,
        documentation: "Base move mnemonic.",
        detail: "Base move mnemonic.",
        insertText: "mov",
        range: range,
      },
      {
        label: "add",
        kind: monaco.languages.CompletionItemKind.Keyword,
        documentation: "Base add mnemonic.",
        detail: "Base add mnemonic.",
        insertText: "add",
        range: range,
      },
      {
        label: "sub",
        kind: monaco.languages.CompletionItemKind.Keyword,
        documentation: "Base sub mnemonic.",
        detail: "Base sub mnemonic.",
        insertText: "sub",
        range: range,
      },
      {
        label: "mul",
        kind: monaco.languages.CompletionItemKind.Keyword,
        documentation: "Base mul mnemonic.",
        detail: "Base mul mnemonic.",
        insertText: "mul",
        range: range,
      },
      {
        label: "lsf",
        kind: monaco.languages.CompletionItemKind.Keyword,
        documentation: "Base lsf mnemonic.",
        detail: "Base lsf mnemonic.",
        insertText: "lsf",
        range: range,
      },
      {
        label: "rsf",
        kind: monaco.languages.CompletionItemKind.Keyword,
        documentation: "Base rsf mnemonic.",
        detail: "Base rsf mnemonic.",
        insertText: "rsf",
        range: range,
      },
      {
        label: "and",
        kind: monaco.languages.CompletionItemKind.Keyword,
        documentation: "Base and mnemonic.",
        detail: "Base and mnemonic.",
        insertText: "and",
        range: range,
      },
      {
        label: "or",
        kind: monaco.languages.CompletionItemKind.Keyword,
        documentation: "Base or mnemonic.",
        detail: "Base or mnemonic.",
        insertText: "or",
        range: range,
      },
      {
        label: "xor",
        kind: monaco.languages.CompletionItemKind.Keyword,
        documentation: "Base xor mnemonic.",
        detail: "Base xor mnemonic.",
        insertText: "xor",
        range: range,
      },
      {
        label: "inc",
        kind: monaco.languages.CompletionItemKind.Keyword,
        documentation: "Base inc mnemonic.",
        detail: "Base inc mnemonic.",
        insertText: "inc",
        range: range,
      },
      {
        label: "dec",
        kind: monaco.languages.CompletionItemKind.Keyword,
        documentation: "Base dec mnemonic.",
        detail: "Base dec mnemonic.",
        insertText: "dec",
        range: range,
      },
      {
        label: "not",
        kind: monaco.languages.CompletionItemKind.Keyword,
        documentation: "Base not mnemonic.",
        detail: "Base not mnemonic.",
        insertText: "not",
        range: range,
      },
      {
        label: "jeq",
        kind: monaco.languages.CompletionItemKind.Keyword,
        documentation: "Base jeq mnemonic.",
        detail: "Base jeq mnemonic.",
        insertText: "jeq",
        range: range,
      },
      {
        label: "jne",
        kind: monaco.languages.CompletionItemKind.Keyword,
        documentation: "Base jne mnemonic.",
        detail: "Base jne mnemonic.",
        insertText: "jne",
        range: range,
      },
      {
        label: "jlt",
        kind: monaco.languages.CompletionItemKind.Keyword,
        documentation: "Base jlt mnemonic.",
        detail: "Base jlt mnemonic.",
        insertText: "jlt",
        range: range,
      },
      {
        label: "jgt",
        kind: monaco.languages.CompletionItemKind.Keyword,
        documentation: "Base jgt mnemonic.",
        detail: "Base jgt mnemonic.",
        insertText: "jgt",
        range: range,
      },
      {
        label: "jle",
        kind: monaco.languages.CompletionItemKind.Keyword,
        documentation: "Base jle mnemonic.",
        detail: "Base jle mnemonic.",
        insertText: "jle",
        range: range,
      },
      {
        label: "jge",
        kind: monaco.languages.CompletionItemKind.Keyword,
        documentation: "Base jge mnemonic.",
        detail: "Base jge mnemonic.",
        insertText: "jge",
        range: range,
      },
      {
        label: "psh",
        kind: monaco.languages.CompletionItemKind.Keyword,
        documentation: "Base psh mnemonic.",
        detail: "Base psh mnemonic.",
        insertText: "psh",
        range: range,
      },
      {
        label: "pop",
        kind: monaco.languages.CompletionItemKind.Keyword,
        documentation: "Base pop mnemonic.",
        detail: "Base pop mnemonic.",
        insertText: "pop",
        range: range,
      },
      {
        label: "cal",
        kind: monaco.languages.CompletionItemKind.Keyword,
        documentation: "Base cal mnemonic.",
        detail: "Base cal mnemonic.",
        insertText: "cal",
        range: range,
      },
      {
        label: "ret",
        kind: monaco.languages.CompletionItemKind.Keyword,
        documentation: "Base ret mnemonic.",
        detail: "Base ret mnemonic.",
        insertText: "ret",
        range: range,
      },
      {
        label: "hlt",
        kind: monaco.languages.CompletionItemKind.Keyword,
        documentation: "Base hlt mnemonic.",
        detail: "Base hlt mnemonic.",
        insertText: "hlt",
        range: range,
      },
    ],
  };
};

export const completionProvidor: monaco.languages.CompletionItemProvider = {
  provideCompletionItems,
};
